apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: nodejs-10-action
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: nodejs-build-bot
          source:
            git:
              url: https://github.com/mrutkows/openwhisk-knative-build.git 
              revision: runtimes 
          template:
            name: kaniko
            arguments:
              - name: IMAGE
                value: docker.io/pritidesai/nodejs-10-action:latest
      revisionTemplate:
        spec:
          container:
            image: docker.io/pritidesai/nodejs-10-action:latest
            imagePullPolicy: Always
